# This workflow will install Python dependencies and execute repo's pre-commit hooks on all files.

name: Code check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  pre-commit-check:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pre-commit via pip
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Execute pre-commit hooks on all files
      run: |
        pre-commit install
        SKIP=no-commit-to-branch pre-commit run --all-files
